# Generated by Django 5.0.4 on 2024-04-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_art_url_nowplayingsong_art'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NowPlayingSong',
        ),
    ]
