# Generated by Django 5.0.4 on 2024-05-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubricks', '0002_alter_rubric_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='time',
        ),
    ]
